package com.alice.muzyka.dto

import java.time.LocalDate

// DTO for creating a blog post, ID is omitted as it will be generated by the backend.
data class BlogPostCreateRequest(
    val bannerSrc: String?,
    val bannerAlt: String?,
    val cardTitle: String,
    val cardAuthor: String?,
    val cardDate: LocalDate,
    val cardBrief: String?,
    val postTitle: String,
    val postContent: String?
)
